version: '3.8'

services:
  portfolio:
    image: danieltjw95/express-portfolio:1.0
    build: 
      context: ./portfolio
    networks: 
      - backend
    environment:
      - DEBUG='express:*'
  
  proxy:
    image: danieltjw95/nginx-reverse:1.0
    build:
      context: ./nginx
    ports:
      - "80:80"
    networks: 
      - frontend
      - backend

networks: 
  frontend:
  backend: